spring:
  datasource:
    password:
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
    allowed:
      resources: /h2-console/**
  flyway:
    baselineOnMigrate: true
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: 600000


jwt:
  key: ${$key-jwt}

aws:
  region: us-east-1
  accessKey: {$access-key}
  secretKey: {$secret-key}
  s3:
    buckets:
      user: {$bucket-user}
      product: {$bucket-product}