spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DB_PASSWORD:1pNEBoFbIaZjDphNf6Uh}
    url: ${DB_URL:jdbc:mysql://containers-us-west-99.railway.app:7011/railway?useTimezone=true&serverTimezone=America/Sao_Paulo}
    username: ${DB_USER:root}
  jpa:
    show:
      sql: true
  flyway:
    baselineOnMigrate: ${FLYWAY_BASE_LINE:true}
  redis:
    host: ${REDIS_HOST:containers-us-west-23.railway.app}
    port: ${REDIS_PORT:7542}
    password: ${REDIS_PASSWORD:q6w9bMo65bb9bH5hhSOC}
    user: ${REDIS_USER:default}
  cache:
    type: redis
    redis:
      time-to-live: 600000
  security:
     oauth2:
       client:
         registration:
           google:
            clientId: ${CLIENT_ID}
            clientSecret: ${CLIENT_SECRET}
jwt:
  key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970