spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DB_PASSWORD}
    url: ${DB_URL:jdbc:mysql://containers-us-west-167.railway.app:6981/railway}
    username: ${DB_USER}
  jpa:
    show:
      sql: true
  flyway:
    baselineOnMigrate: ${FLYWAY_BASE_LINE}
  redis:
    host: redis-15391.c262.us-east-1-3.ec2.cloud.redislabs.com
    port: 15391
    password: fn6C7OeO9NVCETa9HVSWZVIeN96YBl9P
    user: default
  cache:
    type: redis
    redis:
      time-to-live: 600000
  security:
     oauth2:
       client:
         registration:
           google:
            clientId: ${CLIENT_ID}
            clientSecret: ${CLIENT_SECRET}
jwt:
  key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970