spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DB_PASSWORD:}
    url: ${DB_URL:jdbc:mysql://localhost:3306/tcc_bfn?useTimezone=true&serverTimezone=America/Sao_Paulo}
    username: ${DB_USER:root}
  jpa:
    show:
      sql: true
  flyway:
    baselineOnMigrate: true
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: 600000

jwt:
  key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

aws:
  region: ap-southeast-1
  accessKey: AKIAUT6UORFO76RHYDBP
  secretKey: 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
  s3:
    buckets:
      user: user-image-profile-tcc
      product: product-images-tcc