spring:
  datasource:
    password:
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
    allowed:
      resources: /h2-console/**
  flyway:
    baselineOnMigrate: true
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: 600000
  security:
     oauth2:
       client:
         registration:
           google:
            clientId: ${secretId}
            clientSecret: ${secretName}


jwt:
  key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

aws:
  region: eu-west-1
  s3:
    buckets:
      customer: tcc-bfn-image-profile