package com.br.tcc.bfn.utils;

public class BfnConstants {

    public final static String ERRO_SAVE_USER = "CANNOT SAVE OBJECT, CONSULTING YOUR SUPPORT";
    public final static String USER_NOT_FOUND = "USER NOT FOUND!!!";
    public final static String USER_EXIST_BY_EMAIL = "EXIST USER WITH EMAIL, TRY OTHER!!!";
    public final static String REQUEST_IS_NULL = "REQUEST CANNOT BE NULL!!!";
    public final static Long ROLE_DEFAULT = 1L;
    public final static String CATEGORY_NOT_FOUND = "CATEGORY NOT FOUND!!!";
    public final static String ERRO_SAVE_PRODUCT = "CANNOT SAVE OBJECT, CONSULTING YOUR SUPPORT";
    public final static String PRODUCT_NOT_FOUND = "PRODUCT NOT FOUND!!!";
    public final static String ADDRESS_NOT_FOUND = "ADDRESS NOT FOUND!!!";
    public final static String ERRO_GENERIC = "ERROR CONSULTING YOUR SUPPORT TO MORE INFOS";
    public final static String TOKEN_IS_VALID = "THE TOKEN IS STILL VALID FOR USE IN THE API.";
    public final static String INVALID_DOCUMENT = "THE DOCUMENT IS INVALID.";
    public final static String ROLE_ONG = "ROLE_ONG";
    public final static Long ROLE_ADMIN = 2L;
    public final static String ROLE_DEFAULT_USER = "ROLE_USER";
    public static final String DONATION_NOT_FOUND = "DONATION NOT FOUND!";
    public static final String TEMPLATE_CREATE_ORDER_DONATION = "DONATION_ORDER_CREATED";
    public static final String TEMPLATE_NOTIFICATE_INTERMEDIARY = "NOTIFICATE_INTERMEDIARY";
    public static final String TEMPLATE_NOTIFICATE_DONOR = "NOTIFICATE_DONOR";
    public static final String TEMPLATE_NOTIFICATE_RECEIVED_TO_GET_DONATION = "NOTIFICATE_RECEIVED_TO_GET_DONATION";
    public static final String TEMPLATE_NOTIFICATE_DONOR_TO_APPROVE_ORDER_DONATION = "NOTIFICATE_DONOR_TO_APPROVE_ORDER_DONATION";
    public static final String TEMPLATE_NOTIFICATE_RECEIVED_WITH_STATUS_WAITING_DONOR = "NOTIFICATE_RECEIVED_WITH_STATUS_WAITING_DONOR";
    public static final String TEMPLATE_NOTIFICATE_RECEIVED_WITH_STATUS_WAITING_ONG_APPROVED = "NOTIFICATE_RECEIVED_WITH_STATUS_WAITING_ONG_APPROVED";
    public static final String TEMPLATE_NOTIFICATE_RECEIVED_WITH_STATUS_NOT_APPROVED_BY_DONOR = "NOTIFICATE_RECEIVED_WITH_STATUS_NOT_APPROVED_BY_DONOR";
}
